### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by BenJam** [mysociety/panama-theme#104]
>Contáctenos
>If your question isn't answered here, or you just wanted to let us know something about the site, contact us.

should be 

>Contáctenos
>Si no encuentra la respuesta a sus preguntas aquí, o simplemente desea hacernos saber algo sobre la plataforma, Contáctenos.

but isn't in transifex.

**Comment by lizconlan** [comment]
note to self: appears to refer to a page in the help section
