### ISSUE TITLE
remove internal review process OR update guidance

### ISSUE THREAD

**Issue by BenJam** [mysociety/panama-theme#107]
Panama doesn't have the necessary legislation to *enforce* authorities to provide an internal review process however they are happy to keep the feature if a process can be agreed. However the link in 

>If you are dissatisfied by the response you got from the public authority, you have the right to complain (details).

goes to http://foiwiki.com/foiwiki/index.php/Internal_reviews which doesn't concern Panamanian legislation at all. 

I'll update asap.

**Comment by stevenday** [comment]
I've updated this copy in #109 - which now needs updating to have a Spanish version and finished English text. I'm closing this in favour of that.
