### ISSUE TITLE
Update theme to match new request creation process

### ISSUE THREAD

**Issue by stevenday** [mysociety/panama-theme#112]
@garethrees knows more.

**Comment by stevenday** [comment]
@garethrees - I've been through the panama theme creating a new request, and while we don't have all of the same HTML as the current alaveteli theme, everything seems to work after a couple of minor fixes.

I've made a pull request at #114 - can I show you the site tomorrow and see if we're missing anything major?

**Comment by garethrees** [comment]
Sounds good! Maybe "Day 2" in the unstructured day? Add it to the agenda so we don't forget :)
