### ISSUE TITLE
Final issues

### ISSUE THREAD

**Issue by BenJam** [mysociety/panama-theme#92]
Some feedback from @ANTAI this morning:

- [x] check that the request confirmation/email says 30 **calendar** days
- [x] send a test script with some test requests to ANTAI
- [x] remove the donation for mysociety text in on the help page
- [x] check that the statistics are being generated okay (on the admin)
- [x] fully justify the text on the help page
- [x] reduce or move the amount of the law shown
- [x] remove the contactemos pagina from the menu (as it's larger below)
- [x] fully justify as much as possible
- [x] fix padding for the 'Make a request' button (link) on the homepage

**Comment by stevenday** [comment]
I think all of these things have now been done? I'm going to close it for now, re-open if I'm missing something.
